apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: localhost:5000/auth-service:latest
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "postgres-auth"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_DATABASE
              value: "expense_manager_auth"
            - name: JWT_SECRET
              value: "your-super-secret-key"
            - name: JWT_EXPIRATION
              value: "1d"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
    - port: 3000
  selector:
    app: auth-service
