apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-service
  template:
    metadata:
      labels:
        app: expense-service
    spec:
      containers:
        - name: expense-service
          image: localhost:5000/expense-service:latest
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "postgres-expense"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_DATABASE
              value: "expense_manager_expenses"
            - name: JWT_SECRET
              value: "your-super-secret-key"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672"
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: expense-service
spec:
  ports:
    - port: 3001
  selector:
    app: expense-service
