apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: localhost:5000/notification-service:latest
          env:
            - name: NODE_ENV
              value: "production"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672"
            - name: RABBITMQ_NOTIFICATION_QUEUE
              value: "notification_queue"
            - name: EMAIL_HOST
              value: "sandbox.smtp.mailtrap.io"
            - name: EMAIL_USERNAME
              value: "cf9c87ddb4dd70"
            - name: EMAIL_PASSWORD
              value: "f2599055423bfb"
            - name: EMAIL_PORT
              value: "587"
            - name: EMAIL_FROM_NAME
              value: "ExpenseManager-NestJS"
            - name: EMAIL_FROM_ADDRESS
              value: "hello@demomailtrap.co"
          command: ["node", "dist/apps/notification-service/main.js"]
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  ports:
    - port: 3003
  selector:
    app: notification-service
